### ISSUE TITLE
Export never loads

### ISSUE THREAD

**Issue by sbokman** [CartONG/arcgis-rest-service-export#6]
I am trying to export the following ArcGis features, but they never load. Can you help me out?
https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/Landfills/FeatureServer
https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/Landfills/FeatureServer
https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/MRF/FeatureServer
https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/Transfer_Stations/FeatureServer
https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/Waste_Tires/FeatureServer
https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/Solid_Waste/FeatureServer

**Comment by sbokman** [comment]
Realized I didn't click on the layer, nevermind.

**Comment by mmoreno-cart** [comment]
Hi @sbokman, I assume you managed to make it work if you closed the issue. I tried myself the first service (adding the layer ID at the end of the URL) and I got the response quite fast. Could you please describe what was wrong so that we can have it in mind in case we further develop the tool? (we are not continuously updating it)
Thanks

**Comment by sbokman** [comment]
Hello! The reason why it didn't work is because I was on the main GIS hub page, and not on the layer page.
I realized it was my mistake, not the Rest Export Service.

Thank you!
________________________________
